[package]
name = "libp2p-rust-projects"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
libp2p = { version = "0.55.0", features = ["full"] }
serde = { version = "1.0.219", features = ["default", "serde_derive"] }
tokio = { version = "1.45.1", features = ["full"] }